services:
  db:
    image: postgres:15
    container_name: flight_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flights_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flights_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile
    container_name: flights_api
    environment:
      # Compose WITH DB container
      DATABASE_URL: postgresql://postgres:postgres@db:5432/flights_db
      # JWT_SECRET: not-used-in-this-implementation
      # NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  postgres_data:
